# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rohit Gupta
tagline:          Think,Design,Make,Repeat 
description:      'A blog by <a href="www.twitter.com/rohit7gupta">@rohit7gupta</a>'
url:              http://indiantinker.github.io
baseurl:          /

#gems:
 # - jekyll-sitemap

author:
  name:           'Rohit'
  url:            https://twitter.com/rohit7gupta

paginate:         2

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/indiantinker
