# Dependencies
markdown:         redcarpet
highlighter:      pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Rohit Gupta
tagline:          Think,Design,Make,Repeat 
description:      'A blog by <a href="www.twitter.com/rohit7gupta">@rohit7gupta</a>'
url:              http://rohitg.in
baseurl:          /

excerpt_separator: <!--more-->  # you can specify your own separator, of course.

author:
  name:           'Rohit'
  url:            https://twitter.com/rohit7gupta

paginate:         1

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/indiantinker
