# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:	[jekyll-paginate, jekyll-gist]
theme: minima

# Permalinks
permalink:        pretty

# Setup
title:            Rohit Gupta
tagline:          Critical Technologist and Plural optimist
description:      'A blog by <a href="https://twitter.com/rohit7gupta">@rohit7gupta</a>'
url:              http://rohitg.in
baseurl:          /

excerpt_separator: <!--more-->  # you can specify your own separator, of course.

author:
  name:           'Rohit'
  url:            https://twitter.com/rohit7gupta

paginate:         3

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/indiantinker

kramdown:
  input: GFM
  hard_wrap: false
